### PR TITLE
king safety that gains something

### PR DESCRIPTION
**Pull request by nescitus**
53,2% after 500 games
coding style amended
it's funny, but version with parameters close to the original scored best, I still didn't manage to beat original version using extended king attack zone, even though games were much more dynamic

### CODE REVIEW

**Comment by Akusari** [comment]
We'll look at this patch....

Good point about the code style. We only have the sources and follow them. I should write a style guide anyway. For for example we use strict plain C and only use C++ if we have a real speed benefit. This means variables should be declared at the start of an method.

**Comment by Akusari** [comment]
Thanks for your patch, but we like to go another way with king attack. Basicly your idea isn't bad at all. I prefer to play with the attack tables in attack.cpp first. Ryan like to create an attack board (bitboard or some kind of attack table like Rebel) which isn't bad too. We need some tests which one is better. With an attack board we could do more on tactics in evaluation.

**Comment by nescitus** [comment]
Thank You for Your reply, it will be interesting to see data structures
that You are talking about and learn something from them.

As for my idea, a simpler implementation may exist, changing
piece_attack_king() from bool to int and counting attacks. Should I go
ahead with this?

I have tried a few alternative settings in the meantime, but could not
improve over what I sent to You: counting number of attacks, king zone and
parameters unchanged, transparency for Rook/Bishop, no transparency for
Queen. Perhaps You will find this information useful.

Regards,

pk

2014-03-23 7:55 GMT+01:00 Daniel Mehrmann notifications@github.com:

**Comment by Akusari** [comment]
Well, the most importent table is PieceDeltaDelta[][][]. It stores the squares and we should work with this data. We could create a new one or extend the table to store values for a king zone (distance==2 if file +1/-1/0). I need to find time to work on that. Kingattack is currently not the highest topic on our todo list. Material imbalance stuff and outpost (i'm working on that currently) are the highest tasks.

You couldn't improve because your idea has some bugs. We only test at end of board or if another piece blocked the way.

**Pull request closed without merging**
